### ISSUE TITLE
Use config file for TPS workflow inputs

### ISSUE THREAD

**Issue by agitter** [ajshedivy/tps#14]
We discussed using a config or properties file to track all of the input files and settings that a user needs to specify.  That would greatly reduce the number of command line arguments needed.

A YAML file could be one option.  We should look at what other modern software uses.

**Comment by agitter** [comment]
This blog post gives a thorough overview of different file types and associated parsers that are often used for config files: https://hackersandslackers.com/simplify-your-python-projects-configuration/

Using YAML as an example, we could have a config file like
```yaml
tps:
  network: data/networks/input-network.tsv
  timeseries: data/timeseries/median-time-series.tsv
  firstscores: data/timeseries/p-values-first.tsv
  ...

cytoscape: /home/seluser/cytoscape/start.sh
```
